### ISSUE TITLE
Problem with FTTagging module

### ISSUE THREAD

**Issue by adarshp** [adarshp/delphes#1]
@huayangs I’m still having trouble running Delphes with Top Tagging - I'm getting this error:

`** ERROR: can't access input list 'FastJetFinder/jets' in module ‘FTTagging’.`

I think maybe it’s from line 102 of the file [modules/FTTagging.cc](https://github.com/adarshp/delphes/blob/master/modules/FTTagging.cc)

Do you get the same error?

**Comment by adarshp** [comment]
Actually never mind - I just needed to pull the changes from the repo.

**Comment by huayangs** [comment]
Does it work now?

Best,
Huayang

**Comment by adarshp** [comment]
@huayangs Yes, it does!
